Merge branch 'main' into realitySpiral/greetingworkflow

diff --git a/.github/workflows/integrationTests.yaml b/.github/workflows/integrationTests.yaml
--- a/.github/workflows/integrationTests.yaml
+++ b/.github/workflows/integrationTests.yaml
@@ -49,13 +49,17 @@ jobs:
               id: check_api_key
               run: |
                   if [ -z "$OPENAI_API_KEY" ]; then
-                      echo "Error: OPENAI_API_KEY is not set."
-                      exit 1
+                    echo "::set-output name=api_key_present::false"
+                  else
+                    echo "::set-output name=api_key_present::true"
                   fi
-              env:
-                  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
 
             - name: Run integration tests
+              if: steps.check_api_key.outputs.api_key_present == 'true'
               run: pnpm run integrationTests
-              env:
-                  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
+
+            - name: Skip integration tests
+              if: steps.check_api_key.outputs.api_key_present == 'false'
+              run: |
+                  echo "Skipping integration tests due to missing required API keys"
+                  exit 1
