fix: tested and fixed deployment and escrow functionality

diff --git a/.github/workflows/integrationTests.yaml b/.github/workflows/integrationTests.yaml
--- a/.github/workflows/integrationTests.yaml
+++ b/.github/workflows/integrationTests.yaml
@@ -1,4 +1,4 @@
-name: Integration Tests
+name: integration-test
 on:
     push:
         branches:
@@ -6,39 +6,50 @@ on:
     pull_request_target:
         branches:
             - "*"
-
 jobs:
-    integration-tests:
+    smoke-tests:
         runs-on: ubuntu-latest
-        env:
-            OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
         steps:
             - uses: actions/checkout@v4
 
             - uses: pnpm/action-setup@v3
               with:
-                  version: 9.15.0
+                  version: 9.4.0
 
             - uses: actions/setup-node@v4
               with:
-                  node-version: "23.3.0"
+                  node-version: "23"
                   cache: "pnpm"
 
-            - name: Clean up
-              run: pnpm clean
+            - name: Run smoke tests
+              run: pnpm run smokeTests
+    integration-tests:
+        runs-on: ubuntu-latest
+        steps:
+            - uses: actions/checkout@v4
+
+            - uses: pnpm/action-setup@v3
+              with:
+                  version: 9.4.0
+
+            - uses: actions/setup-node@v4
+              with:
+                  node-version: "23"
+                  cache: "pnpm"
 
             - name: Install dependencies
-              run: pnpm install -r --no-frozen-lockfile
+              run: pnpm install -r
 
             - name: Build packages
               run: pnpm build
 
-            - name: Check for API key
+            - name: Run integration tests
+              env:
+                  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
               run: |
                   if [ -z "$OPENAI_API_KEY" ]; then
-                      echo "Error: OPENAI_API_KEY is not set."
-                      exit 1
+                    echo "Skipping integration tests due to missing required API keys"
+                    exit 1
+                  else
+                    pnpm run integrationTests
                   fi
-
-            - name: Run integration tests
-              run: pnpm run integrationTests
