Merge branch 'develop' into dynamic-template

diff --git a/.github/workflows/integrationTests.yaml b/.github/workflows/integrationTests.yaml
--- a/.github/workflows/integrationTests.yaml
+++ b/.github/workflows/integrationTests.yaml
@@ -33,9 +33,12 @@ jobs:
             - name: Build packages
               run: pnpm build
 
-            - name: Run integration tests
-              env:
-                  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
-                  COINBASE_COMMERCE_KEY: ${{ secrets.COINBASE_COMMERCE_KEY }}
+            - name: Check for API key
               run: |
-                  pnpm run integrationTests
+                  if [ -z "$OPENAI_API_KEY" ]; then
+                      echo "Error: OPENAI_API_KEY is not set."
+                      exit 1
+                  fi
+
+            - name: Run integration tests
+              run: pnpm run integrationTests
