Added Setup.sh to scripts

diff --git a/.github/workflows/integrationTests.yaml b/.github/workflows/integrationTests.yaml
--- a/.github/workflows/integrationTests.yaml
+++ b/.github/workflows/integrationTests.yaml
@@ -3,7 +3,7 @@ on:
     push:
         branches:
             - "*"
-    pull_request:
+    pull_request_target:
         branches:
             - "*"
 
@@ -17,11 +17,11 @@ jobs:
 
             - uses: pnpm/action-setup@v3
               with:
-                  version: 9.15.0
+                  version: 9.4.0
 
             - uses: actions/setup-node@v4
               with:
-                  node-version: "23.3.0"
+                  node-version: "23"
                   cache: "pnpm"
 
             - name: Clean up
@@ -33,9 +33,12 @@ jobs:
             - name: Build packages
               run: pnpm build
 
-            - name: Run integration tests
-              env:
-                  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
-                  COINBASE_COMMERCE_KEY: ${{ secrets.COINBASE_COMMERCE_KEY }}
+            - name: Check for API key
               run: |
-                  pnpm run integrationTests
+                  if [ -z "$OPENAI_API_KEY" ]; then
+                      echo "Error: OPENAI_API_KEY is not set."
+                      exit 1
+                  fi
+
+            - name: Run integration tests
+              run: pnpm run integrationTests
